server:
  port: 8001
spring:
  application:
    name: cloud-payment-service #不要轻易修改，要与注册到eureka中的名称保持一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2021?useUnicode=true&characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456
eureka:
    client:
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka
    instance:
      instance-id: payment8001
      prefer-ip-address: true
##      Eureka客户端想服务端发送心跳的时间间隔，单位为秒(默认是30S)
#      lease-renewal-interval-in-seconds: 1
##      Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90S)，超时将剔除服务
#      lease-expiration-duration-in-seconds: 2
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gsh.entities
