server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
#      - id: payment_routh #路由的ID，没有固定的规则但要求唯一，建议配合服务名
##        uri: http://localhost:8001  #匹配后提供服务的路由地址
#        uri: lb://cloud-payment-service
#        predicates:
#              - Path=/payment/** #断言，路径相匹配的进行路由
#              - After=2021-07-17T16:45:49.927+08:00[Asia/Shanghai]

      - id: payment_routh2 #路由的ID，没有固定的规则但要求唯一，建议配合服务名
#        uri: http://localhost:8001  #匹配后提供服务的路由地址
        uri: lb://cloud-payment-service
        predicates:
              - Path=/payment/**  #断言，路径相匹配的进行路由
#              - After=2021-07-17T16:45:49.927+08:00[Asia/Shanghai]
              - Between=2021-07-17T15:45:49.927+08:00[Asia/Shanghai],2021-07-17T16:45:49.927+08:00[Asia/Shanghai]
#              - Cookie=username,tt
#              - Header=X-Request-Id, \d+
#              - Host=**.gsh.com
              - Method=Get
              - Query=username, \d+
#     filter:
#       add-request-parameter:
#         enabled: true
#    filters:


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
      service-url:
         register-with-eureka: true
         fetch-registry: true
         defaultZone: http://eureka7001.com:7001/eureka
