server:
  port: 8001
spring:
  application:
    name: cloud-hystrix-payment-service #不要轻易修改，要与注册到eureka中的名称保持一致

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

